#!/bin/bash

echo "🔍 Ollama 터널 URL 찾기"
echo "========================================"
echo ""
echo "유송님, 노트북에서 실행 중인 Cloudflare 터널의 URL을 확인해주세요!"
echo ""
echo "방법 1: 터널 실행 창 확인"
echo "  - 'cloudflared tunnel' 또는 'cloudflare quick tunnel' 실행 창"
echo "  - 'https://xxxxx.trycloudflare.com' 형태의 URL"
echo ""
echo "방법 2: 노트북에서 이 명령 실행"
echo "  Windows: netstat -ano | findstr :11434"
echo "  Mac/Linux: lsof -i :11434"
echo ""
echo "방법 3: Ollama 로그 확인"
echo "  - Ollama 실행 시 출력된 URL"
echo ""
echo "========================================"
echo ""
echo "찾은 URL을 알려주시면 바로 설정해드리겠습니다!"
echo ""
echo "예시:"
echo "  https://xxxx-yyyy-zzzz.trycloudflare.com"
echo ""
