tunnel: 9d769497-4d6f-45a8-9236-ee9f214e5d8e
credentials-file: C:\Users\wordy\.cloudflared\9d769497-4d6f-45a8-9236-ee9f214e5d8e.json

ingress:
  - hostname: leemay.thetheunique.com
    service: http://localhost:5001

  - hostname: ai_trading.thetheunique.com
    service: http://localhost:5000

  - service: http_status:404